image: centos:latest

variables:
    NPM_TOKEN: SECURE
    FIREFOX_BIN: /usr/bin/firefox
    NO_PROXY: 'localhost, 0.0.0.0/4201, 0.0.0.0/9876'

stages:
    - test
    - release
    - cleanup

test:all:
    stage: test
    script:
        - yum install -y epel-release
        - yum update -y
        - yum install -y git wget bzip2 firefox npm gtk3
        - wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
        - tar vjxf firefox.tar.bz2
        - rm -rf /usr/bin/firefox
        - ln -s /firefox/firefox $FIREFOX_BIN
        - npm install
        - export
        - npm test
        - firefox -headless

release:npm:
    stage: release
    script:
        - yum install -y epel-release
        - yum update -y
        - yum install -y npm
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - npm publish
    only:
        - tags

cleanup:secrets:
    stage: cleanup
    when: always
    script:
        - rm -f ~/.npmrc
