image: centos:latest

variables:
    NPM_TOKEN: SECURE

stages:
    - test
    - release
    - cleanup

test:all:
    stage: test
    script:
        - yum install -y git gcc-c++ make firefox
        - curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
        - yum install -y nodejs
        - npm install
        - npm test

release:npm:
    stage: release
    script:
        - yum install -y git gcc-c++ make
        - curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
        - yum install -y nodejs
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - echo "unsafe-perm = true" >> ~/.npmrc
        - npm install
        - npm publish
    only:
        - tags

cleanup:secrets:
    stage: cleanup
    when: always
    script:
        - rm -f ~/.npmrc
