image: centos:latest

variables:
    NPM_TOKEN: SECURE

stages:
    - test
    - release
    - cleanup

test:all:
    stage: test
    script:
        - yum install -y epel-release
        - yum update -y
        - yum install -y git wget bzip2 firefox npm
        - rm /usr/bin/firefox
        - wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
        - tar jxf firefox.tar.bz2
        - export FIREFOX_BIN=/firefox/firefox
        - npm install
        - npm test

release:npm:
    stage: release
    script:
        - yum install -y epel-release
        - yum update -y
        - yum install -y npm
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - npm publish
    only:
        - tags

cleanup:secrets:
    stage: cleanup
    when: always
    script:
        - rm -f ~/.npmrc
