image: centos:latest

variables:
    NPM_TOKEN: SECURE

stages:
    - test
    - release
    - cleanup

test:all:
    stage: test
    script:
        - yum install -y git gcc-c++ make
        - echo -e "[google-chrome]\nname=google-chrome\nbaseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\ngpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub" > /etc/yum.repos.d/google-chrome.repo
        - curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
        - yum install -y google-chrome-stable nodejs
        - npm install
        - npm test

release:npm:
    stage: release
    script:
        - yum install -y gcc-c++ make
        - curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
        - yum install -y nodejs
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - echo "unsafe-perm = true" >> ~/.npmrc
        - npm publish
    only:
        - tags

cleanup:secrets:
    stage: cleanup
    when: always
    script:
        - rm -f ~/.npmrc
