export default {
  SET_DATA: 'SET_DATA',
  SET_REQUEST_MANAGER: 'SET_REQUEST_MANAGER',
  SET_CHART_MANAGER: 'SET_CHART_MANAGER',
  SET_STATE_MANAGER: 'SET_STATE_MANAGER',
  SET_SUBSETS: 'SET_SUBSETS',
  SET_FILTER: 'SET_FILTER',
  SET_TASK: 'SET_TASK',
  UNSET_TASK: 'UNSET_TASK',
  SET_CONTROL_PANEL: 'SET_CONTROL_PANEL',
  SET_OPTIONS: 'SET_OPTIONS'
}
